version: '3.9'

services:
  postgres:
    image: postgres:latest
    container_name: postgres
    restart: always
    ports:
      - 5432:5432
    volumes:
      - pg-data:/data/postgres
    env_file:
      - ./.env

  redis:
    image: redis:latest
    container_name: redis
    restart: always
    ports:
      - 6379:6379
    volumes:
      - rd-data:/data/redis

volumes:
  pg-data:
  rd-data: